name: Excavator

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Excavate
        uses: Ash258/Scoop-GithubActions@stable
        env:
          GITH_EMAIL: kidonng@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
